name: fyp2
description: "Personal Financial Tracker Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  # AUDIO / VOICE RECORDING (COMPLETE)
  flutter_sound: ^9.2.13
  audio_session: ^0.1.18
  permission_handler: ^11.3.1

  # NETWORK
  flutter_stripe: ^10.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  image_picker: ^1.0.7

  http: ^1.2.2

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.3

  # Charts
  fl_chart: ^0.65.0
  flutter_markdown: ^0.7.7+1

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/kangaroo.png